n_jobs: 6 # いくつ並列処理させるか

params: 
  measure:
    cource:
      #- train: [1,2,4,5,6,7,8,9,10,11,12,13,14,15]
      - train: [2,5,6,13,15]
        val: [4,8,11,14]
        predict: 1
         
      - train: [2,5,6,13,15]
        val: [4,8,11,14]
        predict: 3

      - train: [2,5,6,13,15]
        val: [4,8,11,14]
        predict: 7


    start_ratio: 0
    end_ratio: 1
    data_axis: distance
    sampling_rate: 0.03925 
    
  model:
    rnn_type: SimpleRNN
    optimizer_type: Adam
    in_features: 1
    input_len: [5,10]
    hidden_nums: 
      - [20]
    out_steps_num: 1
    batch_size: 128
    predict_batch_size: 64
    epochs: 100
    learning_rate: 0.0005
    patience: 20
  
  save:
    recursive_num: 500
    plot_start: 100
    plot_range: 50

    use_mlflow: true
    experiment_name: test-meas-v3
    #experiment_name: test-meas

    base_dir: runs